### ISSUE TITLE
Winter indexing and plots

### ISSUE THREAD

**Issue by Kazjon** [Kazjon/birdgrid#23]
On the winter plots the test months are not the last months being plotted -- the rest of the test year is being displayed _after_ them.  That looks very strange.  Could we prevent data after the current test data from being displayed?

Also: For the test year's non-seasonal datapoints, are we displaying the real data, or predictions?

**Comment by SwarnaVallurupalli** [comment]
Since we are considering winter months of current test year as 12th month of previous year and 1st,2nd month of current test year, You might see one data point before the current test year (i.e 12th month test data point of previous year).  Is that answering your question correctly? I don't understand the issue clearly, could you be a bit more specific about the issue.
And regarding the Non-seasonal datapoints, we are displaying the real data.

**Comment by Kazjon** [comment]
![turdus_migratorius- 44 - -105 -2007-winter](https://cloud.githubusercontent.com/assets/3923214/19015659/37ba16ca-87d6-11e6-8a7c-c9b1f7277ca2.png)

Take a look at this image. It's for winter 2007, but it displays the remaining 10 months of 2007 as well -- to the right of the three black dots.  That's confusing.  The test data should be the last thing displayed.

**Comment by SwarnaVallurupalli** [comment]
Oh I was displaying the Non-seasonal data points of Test Data too . I will change that so that only Test Data will be displayed.
